#!/bin/bash
#----------------------------------------------------------------------------------------------------
threshold=${BLOCK_INSTANCE:-5};
load=$(cut -d ' ' -f1 /proc/loadavg);

case $BLOCK_BUTTON in
	2) gnome-terminal -- 'htop' ;;
esac

#Display as red if load exceeds threshold
if (( $(echo "$load $threshold" | awk '{print ($1 > $2)}') )); then
	echo "<span foreground='red'>$load</span>";
else echo $load;
fi
