#!/bin/bash
#----------------------------------------------------------------------------------------------------
#Mouse actions for the block
SINK=$( pactl list short | grep RUNNING | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,' ) # grabs active sink
VOLUME=$( pactl list sinks | grep '^[[:space:]]Volume:' | head -n $SINK | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )


case $BLOCK_BUTTON in
	1) pactl set-sink-mute $SINK toggle ;;
	4) pactl set-sink-volume $SINK +5% ;;
	5) pactl set-sink-volume $SINK -5% ;;
esac

# Check current mute status, hint: check after toggling
ISMUTE=$( pactl list sinks | grep '^[[:space:]]Mute:' | head -n $SINK | tail -n 1 | sed -e 's,.*\(yes\|no\),\1,' )

#Display volume
if [ "$ISMUTE" = "yes" ]; then
	echo 🔇 $VOLUME%
else
	echo 🔊 $VOLUME%
fi

