#!/bin/bash
#----------------------------------------------------------------------------------------------------
#Mouse actions for the block
SINK=$( pactl list short | grep RUNNING | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,' ) # grabs active sink (number)

case $BLOCK_BUTTON in
	1) pactl set-sink-mute $SINK toggle ;;
	4) pactl set-sink-volume $SINK +5% ;;
	5) pactl set-sink-volume $SINK -5% ;;
esac

# Check current mute status and volume, hint: check after changing it
VOLUME=$( pactl list sinks | sed -n "H; /Sink #$SINK/h;"'${g;p;}' | grep '^[[:space:]]Volume:' | head -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )  # show rest of file after Sink #Number, use first volume found
ISMUTE=$( pactl list sinks | sed -n "H; /Sink #$SINK/h;"'${g;p;}' | grep '^[[:space:]]Mute:' | head -n 1 | sed -e 's,.*\(yes\|no\),\1,' )

#Display volume
if [ "$ISMUTE" = "yes" ]; then
	echo 🔇 $VOLUME%
else
	echo 🔊 $VOLUME%
fi

